// SPDX-License-Identifier: MIT
#include "App.h"

const char SETUP_SSID[] = "Nerd-Clock-Setup";
const char SETUP_PASSWORD[] = "NerdClock2026";
WiFiManager wifiManager;
ArduinoLEDMatrix matrix;
bool matrixReady = false;
uint8_t matrixFrame[8][12] = {};
bool matrixAPShown = false;
bool matrixIPActive = false;
char matrixIP[16] = {};
uint32_t matrixIPStarted = 0;
uint32_t lastMatrixStep = 0;
int16_t matrixScrollX = 12;
char serialCommand[24] = {};
uint8_t serialUsed = 0;
uint32_t secondsOfDay = 0;
uint32_t utcEpoch = 0;
bool timeSynced = false;
WiFiUDP ntpUDP;
IPAddress ntpAddress;
uint8_t ntpToken[8] = {};
bool udpReady = false;
bool ntpPending = false;
bool wifiConnected = false;
bool ntpAttempted = false;
bool ntpSucceeded = false;
bool noModuleReported = false;
uint32_t lastNetworkCheck = 0;
uint32_t lastNtpAttempt = 0;
uint32_t lastNtpSuccess = 0;
uint32_t ntpSentAt = 0;
uint32_t secondTick = 0;
FspTimer displayTimer;
volatile uint8_t pendingSegments[8] = {};
volatile uint8_t pendingRing[8] = {};
volatile bool pendingReady = false;
uint8_t activeSegments[8] = {};
uint8_t activeRing[8] = {};
bool displayRunning = false;
uint32_t renderedTime = 0xFFFFFFFFUL;
ClockSettings settings = {};
DisplayMode displayMode = MODE_CLOCK;
const char *const RING_NAMES[4] = {"point", "fill", "drain", "inverse"};
char displayText[5] = {};
char visibleText[5] = "----";
uint32_t timerStarted = 0;
uint16_t timerDuration = 0;
uint16_t timerRemaining = 0;
uint32_t timerSegmentMs = 0;
bool timerPaused = false;
bool dateActive = false;
uint32_t dateStarted = 0;
uint32_t dateTimeoutMs = 0;
uint32_t textStarted = 0;
uint32_t textTimeoutMs = 0;
volatile bool alarmActive = false;
volatile uint32_t alarmStarted = 0;
bool timerEventPending = false;
uint32_t timerEventEpoch = 0;
uint16_t timerEventDuration = 0;
bool discoveryPending = false;
uint8_t discoveryIndex = 0;
char discoveryID[32] = {};
uint8_t discoverySent = 0;
bool discoveryFailed = false;
bool discoveryAttempted = false;
uint32_t lastDiscoveryAttempt = 0, lastDiscoveryComplete = 0;
bool discoveryCompleted = false;
bool displayDirty = true;
volatile uint8_t displayBrightness = 100;
bool settingsDirty = false;
uint32_t settingsChanged = 0;
WiFiClient mqttTransport;
PubSubClient mqtt(mqttTransport);
char mqttClientID[32] = {};
uint32_t lastMqttAttempt = 0;
bool mqttAttempted = false;
bool stateDirty = true;
uint32_t lastMqttState = 0;
WiFiServer appServer(80);
WiFiClient appClient;
bool appClientActive = false;
char appRequest[3072] = {};
size_t appUsed = 0, appHeaderSize = 0, appBodySize = 0;
uint32_t appClientSince = 0;
int previousManagerStatus = -1;
